name: sessions
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.2.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: "0.7.0"
  firebase_database: ^6.0.0
  firebase_storage: any
  firebase_auth: ^0.20.0+1
  firebase_messaging: any
  expansion_tile_card: ^1.1.0
  motion_tab_bar: ^0.1.5
  provider: ^4.3.2+2
  shared_preferences: any
  path_provider: ^2.0.0
  http: any
  googleapis_auth: any
  share: any
  flutter_calendar_carousel: ^1.5.2
  syncfusion_flutter_datepicker: ^19.1.69-beta
  nanoid: ^1.0.0
  top_snackbar_flutter: ^1.0.0
  image_picker: any
  flutter_dotenv: ^5.0.0
  google_fonts: any
  email_validator: ^2.0.1
  cached_network_image: any


dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - images/